const data = [
  {
   "id": 1,
   "title": "Take Care Good Night",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMzAwNjRiOTctMjVkMi00NWNkLTk4YjItNjZmYTk4N2RhZWUyXkEyXkFqcGdeQXVyOTE4NDY3MDQ@._V1_.jpg",
   "director": "Girish Joshi",
   "cast": "Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",
   "rating": "13+",
   "duration": "110 min",
   "show_time": 9,
   "description": "A Metro Family decides to fight a Cyber Criminal threatening their stability and pride."
  },
  {
   "id": 2,
   "title": "Venky Mama",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZTU2NzJmYjgtNzAzZi00NzE4LTgyZDUtODJlY2FjYzZhYTA0XkEyXkFqcGdeQXVyNjE1OTQ0NjA@._V1_.jpg",
   "director": "KS Ravindra(Bobby)",
   "cast": "Venkatesh, Chaitanya, Payal Rajput, Raashi Khanna",
   "rating": "13+",
   "duration": "141 min",
   "show_time": 11,
   "description": "Venkataratnam, son of famous astrologer Ram Narayan, lands in a military cantonment region one week after a major terrorist attack. When interrogated by the military police, he tells them he came in search of his nephew, Karthik, and tells them his story."
  },
  {
   "id": 3,
   "title": "Under Western Stars",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYjUxOGExZmYtMGYzOC00MGY3LTg2ZGItNDZjNjlhNjkwZGIzXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_.jpg",
   "director": "Joseph Kane",
   "cast": "Roy Rogers, Smiley Burnette, Carol Hughes, Maple City Four, Guy Usher, Tom Chatterton, Kenneth Harlan, Alden 'Stephen' Chase, Brandon Beach, Earl Dwire, Jean Fowler, Dora Clement, Dick Elliott, Burr Caruth, Slim Whitaker, Jack Rockwell, Frankie Marvin, Roy Bucko, Fred Burns, Bob Card, Tommy Coats, Tex Cooper, Art Dillard, Curley Dresden, Herman Hack, Henry Hall, Earle Hodgins, Jack Ingram, Art Janes, Jane Keckley, Jack Kirk, Merrill McCormick, Fritz Meissner, George Montgomery, Milburn Morante, George Morrell, Jack O'Shea, Pat Petterson, Al Rice, Duke Taylor, Trigger, Bill Wolfe",
   "rating": "13+",
   "duration": "60 min",
   "show_time": 13,
   "description": "Roy is talked into running for Congress against crooked interests in order to bring water to his district. He must convince a fellow congressman how important the water is to his constituents. This is Roy's first starring film."
  },
  {
   "id": 4,
   "title": "Transmilitary",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMmJkNDRiNGItZjZkNi00Njg5LTgxNWMtYmRhYWNmM2RlMGRjXkEyXkFqcGdeQXVyNjE3NjI4NDI@._V1_.jpg",
   "director": "Gabriel Silverman",
   "cast": "Laila Ireland, Logan Ireland, Jennifer Peace, El Cook, Sue Fulton",
   "rating": "16+",
   "duration": "93 min",
   "show_time": 15,
   "description": "At a time when transgender people are banned from serving in the U.S. military, four transgender troops risking discharge fight to attain the freedom they so fiercely protect. 2018 SXSW Audience Award Winner, Best Documentary."
  },
  {
   "id": 5,
   "title": "Tom Sawyer & Huckleberry Finn",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMjI5MjY3NDYxOV5BMl5BanBnXkFtZTgwODM5NjQ3MzE@._V1_.jpg",
   "director": "Jo Kastner",
   "cast": "Joel Courtney, Jake T. Austin, Val Kilmer",
   "rating": "PG-13",
   "duration": "91 min",
   "show_time": 16,
   "description": "Tom Sawyer and his pal Huckleberry Finn have great adventures on the Mississippi River, pretending to be pirates, attending their own funeral and witnessing a murder."
  },
  {
   "id": 6,
   "title": "Todo Incluido",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNjlkMjIyNWUtOTJjOC00YTI5LTgzYjQtNjNjYWNmMjFjYzkzXkEyXkFqcGdeQXVyODU4MjAxOQ@@._V1_FMjpg_UX1000_.jpg",
   "director": "Roberto ",
   "cast": "Fausto Mata, Cuqun Victoria",
   "rating": "13+",
   "duration": "100 min",
   "show_time": 18,
   "description": "A group of insurance employees go to a sales convention at a beach resort in Punta Cana, where they get involved in various situations."
  },
  {
   "id": 7,
   "title": "Tiger Zinda Hai",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTdlNjE5MGYtODliNy00NGI4LWExMDItYzZmMzdmM2E1ZjRkXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
   "director": "Ali Abbas Zafar",
   "cast": "Salman Khan, Katrina Kaif, Paresh Rawal, Girish Karnad, Anant Vidhaat, Kumud Kumar Mishra, Angad Bedi, Sajjad Delafrooz",
   "rating": "13+",
   "duration": "159 min",
   "show_time": 20,
   "description": "When a group of Indian and Pakistani nurses are held hostage in Iraq by the militant Abu Usman, Indian intelligence (RAW) tracks down the reclusive agent Tiger 8 years after he fled with former Pakistani intelligence (ISI) agent Zoya. Joining forces in the name of humanity, Tiger and Zoya lead a team of RAW and ISI agents to covertly enter the hospital where the nurses are trapped."
  },
  {
   "id": 8,
   "title": "The Wereth Eleven",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTA4NTY5MTExMTheQTJeQWpwZ15BbWU3MDc5ODY1MDQ@._V1_.jpg",
   "director": "Robert Child",
   "cast": "Corey Reynolds, Ken Arnold",
   "rating": "13+",
   "duration": "61 min",
   "show_time": 21,
   "description": "During World War II, 1.2 million African-Americans served in America's Armed Forces. Fully 125,000 served overseas. 708 were killed. Among these were The Wereth Eleven. Their story was lost to history. Until now."
  },
  {
   "id": 9,
   "title": "The Wedding Night",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZjAyMDFiZGMtOWViNi00YTliLThjMDctNjQzN2RkNGE4NWQ4XkEyXkFqcGdeQXVyMjIxMzkyMDg@._V1_.jpg",
   "director": "King Vidor",
   "cast": "Gary Cooper, Anna Sten, Ralph Bellamy",
   "rating": "13+",
   "duration": "79 min",
   "show_time": 22,
   "description": "This romantic tragedy centers on the star-crossed love between a troubled and married writer and the beautiful Polish girl who becomes his inspiration. As the girl and the writer get to know each other, he learns that her stern father has betrothed her to a man she does not love."
  },
  {
   "id": 10,
   "title": "The Uncomfortable Truth",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYmVkNWQ2MzktNGI4ZC00MDAwLTlmYjMtMjMzMDJiNGU1ZmU5XkEyXkFqcGdeQXVyMTQ2MjQ3NzM@._V1_.jpg",
   "director": "Loki Mulholland",
   "cast": "Loki Mulholland, Luvaghn Brown, Joan Trumpauer Mulholland",
   "rating": "13+",
   "duration": "85 min",
   "show_time": 9,
   "description": "When the son of Civil Rights Hero, Joan Trumpauer Mulholland, dives into the 400 year history of institutional racism in America he is confronted with the shocking reality that his family helped start it all from the very beginning. A comprehensive and insightful exploration of the origins and history of racism in America told through a very personal and honest story."
  },
  {
   "id": 11,
   "title": "The Spirit of Christmas",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYzcyM2MxNzMtYzEzNi00MjRlLWI2YTItM2U0MWZlZDVkNjNhL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTU5MjU5MTM@._V1_.jpg",
   "director": "David Jackson",
   "cast": "Thomas Beaudoin, Kati Salowsky, Steven A. Miller",
   "rating": "PG",
   "duration": "91 min",
   "show_time": 11,
   "description": "12 days before Christmas, Kate is trying to close the sale of a historic inn, only to find Daniel, the ghost of a man who died a century ago, and he needs her help to unravel the mystery of his annual holiday haunting."
  },
  {
   "id": 12,
   "title": "The Speed of Thought",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDc2MDQzNTE1OV5BMl5BanBnXkFtZTgwMjcyODkwMzE@._V1_.jpg",
   "director": "Evan Oppenheimer",
   "cast": "Nick Stahl, Mia Maestro, Taryn Manning, Wallace Shawn, Blair Brown",
   "rating": "13+",
   "duration": "94 min",
   "show_time": 13,
   "description": "Joshua Lazarus is a scoper, a telepath who can literally enter other people's thoughts. But Joshua's gift is also his downfall scopers go insane by the age of 29. And Joshua has just turned 28. While on a government spy mission, Joshua falls in love with a fellow scoper. As truths start to unravel and new worlds begin to open, the two lovers battle to spend their few "
  },
  {
   "id": 13,
   "title": "Tel Aviv On Fire",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDdmZGZkMzctODUxYy00MDllLTk0YWItZjI2M2UyY2IzZjA2XkEyXkFqcGdeQXVyMjUzMTYzMDI@._V1_.jpg",
   "director": "Sameh Zoabi",
   "cast": "Lubna Azabal, Kais Nashif",
   "rating": "13+",
   "duration": "96 min",
   "show_time": 15,
   "description": "Salam, an inexperienced young Palestinian man, becomes a writer on a popular soap opera after a chance meeting with an Israeli soldier. His creative career is on the rise - until the soldier and the show's financial backers disagree about how the show should end, and Salam is caught in the middle."
  },
  {
   "id": 14,
   "title": "Sye Raa Narasimha Reddy (Hindi)",
   "image_url": "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/a6fe2f51cfd16593ac158a14dc07fe5cd0e6cb7ff77601adeb4a05cf719b3b0d._RI_TTW_.jpg",
   "director": "Surrender Reddy",
   "cast": "Chiranjeevi, Amitabh Bachchan, Sudeep, Jagapathi Babu, Vijay Sethupathi, Nayanthara, Ravi Kishan, Nassar, Tamannaah Bhatia",
   "rating": "13+",
   "duration": "170 min",
   "show_time": 16,
   "description": "This film is about the first revolt of any kind (1847) against the British Raj in India anchored by Uyyalawada Narasimha Reddy aka Lion of Renadu (A region in Rayalaseema- Andhra Pradesh), nickname with which he was fondly called by his followers."
  },
  {
   "id": 15,
   "title": "Super Size Me 2: Holy Chicken!",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMWVkOTBjMWYtNzE4Zi00MGU5LWI0YTktZWM2ZmQ2ZDFiYzU3XkEyXkFqcGdeQXVyMjE4NzUxNDA@._V1_.jpg",
   "director": "Morgan Spurlock",
   "cast": "Morgan Spurlock",
   "rating": "PG-13",
   "duration": "103 min",
   "show_time": 18,
   "description": "Muckraking filmmaker Morgan Spurlock reignites his battle with the food industry - this time with Big Chicken - as he opens his own fast food restaurant."
  },
  {
   "id": 16,
   "title": "Storm Boy",
   "image_url": "https://m.media-amazon.com/images/M/MV5BOGQzOTRlMTUtZTM4ZS00OTkwLWIxZTMtMDcyYmQ1YWNmMGMyXkEyXkFqcGdeQXVyMTI4Mjg4MjA@._V1_.jpg",
   "director": "Shawn Seet",
   "cast": "Jai Courtney, Geoffrey Rush, Finn Little, Trevor Jamieson, Morgan Davies, Eric Thomson, Natasha Wanganeen, Luca Sardelis, Michelle Nightingale",
   "rating": "PG",
   "duration": "99 min",
   "show_time": 20,
   "description": "When Michael Kingley, a successful retired businessman starts to see images from his past that he can't explain, he's forced to remember his childhood and how, as a boy, he rescued and raised an extraordinary orphaned pelican, Mr Percival. Based on the classic Australian novel. Earned the coveted DOVE Seal of Approval."
  },
  {
   "id": 17,
   "title": "Searching for Augusta: The Forgotten Angel of Bastogne",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTVhNjg0NjItYzY4OS00ODU3LTkzZmUtNDQ2NmRmMzY0OGE0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNzA1NzQ4Mjg@._V1_FMjpg_UX1000_.jpg",
   "director": "Mike Edwards",
   "rating": "13+",
   "duration": "74 min",
   "show_time": 21,
   "description": "This true story begins with two nurses, Renee LeMaire and Augusta Chiwy, as they treat patients in the Bastogne aid station. Renee was killed on Christmas Eve and became famous as \"The Angel of Bastogne.\" Augusta's story was lost to history for sixty-five years. Augusta Chiwy's story is one of great courage and heroism in the face of racial discrimination."
  },
  {
   "id": 18,
   "title": "Sand Castles",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTk4NzQ4OTYyMF5BMl5BanBnXkFtZTgwMjg3OTI3NzE@._V1_.jpg",
   "director": "Clen",
   "cast": "Jordon Hodges, Anne Winters, Randy Spence, Clint Howard",
   "rating": "18+",
   "duration": "94 min",
   "show_time": 22,
   "description": "In rural Indiana, the Daly family wrestles with the mysterious return of Lauren, a daughter kidnapped over a decade ago while her brother Noah was supposed to be watching her. Their uncle, Tommy, then a sheriff's deputy, was unable to find her, and her case remained unresolved.."
  },
  {
   "id": 19,
   "title": "Same Kind of Different as Me",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZDVlZTJmM2QtNjA3YS00NTcxLTlmYmEtNTAzY2E0YzJkNGQ2XkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_.jpg",
   "director": "Michael Carney",
   "cast": "Greg Kinnear, Renee Zellweger, Djimon Hounsou, Jon Voight",
   "rating": "PG-13",
   "duration": "119 min",
   "show_time": 9,
   "description": "From The NY Times bestseller comes an inspirational true story about two men from drastically different backgrounds, who develop a surprising bond that will lead them on the most remarkable journey of their lives and forge an everlasting friendship."
  },
  {
   "id": 20,
   "title": "Rumble: The Indians Who Rocked the World",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNzg1ODY2YmItNjZlZC00MTEzLTlmMTAtNDA5NzVkMzRlN2U4XkEyXkFqcGdeQXVyODM3MjA1NA@@._V1_.jpg",
   "director": "Catherine Bainbridge, Alfonso Maiorana (Co-Director)",
   "cast": "Link Wray, George Clinton, Buffy Sainte-Marie, Martin Scorsese, Slash, Quincy Jones",
   "rating": "13+",
   "duration": "102 min",
   "show_time": 11,
   "description": "This revelatory documentary brings to light the profound and overlooked influence of Indigenous people on popular music in North America. The films focuses on music icons like Link Wray, Jimi Hendrix, Buffy Sainte-Marie, Taboo (The Black Eyed Peas), Charley Patton, Mildred Bailey, Jesse Ed Davis, Robbie Robertson, and Randy Castillo."
  },
  {
   "id": 21,
   "title": "Radioactive",
   "image_url": "https://m.media-amazon.com/images/M/MV5BY2MxOTllN2EtZTE3NC00MmQwLTg0ZWQtMjM1ZjVmZGYxYjdlXkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
   "director": "Marjane Satrapi",
   "cast": "Rosamund Pike, Sam Riley, Aneurin Barnard, Simon Russell, Katherine Parkinson, Sian Brooke, Anya Taylor-Joy",
   "rating": "PG-13",
   "duration": "110 min",
   "show_time": 13,
   "description": "Pioneer Rebel  Genius | Don miss Rosamund Pike in the incredible, true-story"
  },
  {
   "id": 22,
   "title": "Race 3",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMzQ4ZTc5ZTItYWRhNi00YTJjLWI4NGMtNjA0ODQ1ZDQxNzkyXkEyXkFqcGdeQXVyNjc4NjAxMzM@._V1_.jpg",
   "director": "Remo Dsouza",
   "cast": "Anil Kapoor, Salman Khan, Jacqueline Fernandez, Bobby Deol, Daisy Shah, Saqib Saleem, Freddy Daruwala",
   "rating": "13+",
   "duration": "159 min",
   "show_time": 15,
   "description": "Race 3 is the grand saga of a family that deals in borderline crime but is ruthless and vindictive. Characters change their characteristics at the blink of an eye as the story rushes towards a high octane climax with betrayal, fast guns, fast cars and sleek action never seen before on the Indian screen. Action and drama that leads to a shocking twist in the climax that takes your breath away."
  },
  {
   "id": 23,
   "title": "Raazi",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZmVhN2JlYjEtZWFkOS00YzE0LThiNDMtMGI3NDA1MTk2ZDQ2XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
   "director": "Meghna Gulzar",
   "cast": "Alia Bhatt, Vicky Kaushal",
   "rating": "13+",
   "duration": "137 min",
   "show_time": 16,
   "description": "Set in 1971, when the winds of war were blowing between India and Pakistan, Raazi an adaptation of Harinder Sikka novel Calling S"
  },
  {
   "id": 24,
   "title": "Pure the movie series 2",
   "image_url": "https://m.media-amazon.com/images/M/MV5BOWNmZGIxY2ItNDFiZS00ZWFkLTk4ZmQtYzMzOThhMGE5NDRlXkEyXkFqcGdeQXVyNTk2MDMwMzc@._V1_FMjpg_UX1000_.jpg",
   "director": "AK. Reed Films (Amire k reed)",
   "cast": "Efrain Esquilin, John Stover, LaMar Mackey, Fonz Carter, Lajuan Rowe, Terrance Brown, Mr 716 Big Miz, Martellous Jones, Luna Smith, Duece King",
   "rating": "18+",
   "duration": "112 min",
   "show_time": 18,
   "description": "The streets of Buffalo heat up as Bags and his crew from the West-side search for the culprits behind the murder of Yg's Brother Gamble. Events take a turn once Trish gets caught up with the enemy and have to make a decision that may cost her everything. In this action packed film of money, drugs and deceit, there's no telling who may become the ultimate sacrifice."
  },
  {
   "id": 25,
   "title": "Professor Shanku O El Dorado",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYjAzYjY1YTctMjIxZi00ZTM1LWJkNmItMzEwZGY5NzhiNDUxXkEyXkFqcGdeQXVyODQzOTE0NzU@._V1_.jpg",
   "director": "Sandip Ray",
   "cast": "Dhritiman Chatterjee, Subhasish Mukhopadhyay, Eduardo Munniz",
   "rating": "13+",
   "duration": "92 min",
   "show_time": 20,
   "description": "A world of myths, superpowers, and science - and Prof Shanku! Catch India's first science-fiction, with some \"Ray\" magic."
  },
  {
   "id": 26,
   "title": "H.P. Lovecraft's The Deep Ones",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMmYxMTBlZGYtOGI0My00ZWQ4LWE3ZmYtNDMzYmZhNmFjNDc4XkEyXkFqcGdeQXVyNjY1ODUzNw@@._V1_.jpg",
   "director": "Chad Ferrin",
   "cast": "Gina La Piana, Robert Miano, Johann Urb, Silvia Spross",
   "rating": "18+",
   "duration": "83 min",
   "show_time": 21,
   "description": "A married couple rents a beachside cottage only to be surrounded by peculiar neighbors and occurrences. They soon discover they are in the grips of a mysterious cult and their ancient sea god in this tale from Sci-Fi icon, H.P. Lovecraft."
  },
  {
   "id": 27,
   "title": "MACHO: THE HECTOR CAMACHO STORY",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDgwMjljYTMtZTQ3MC00ZWJjLWI1Y2MtYThjMmUwN2FhMmMxXkEyXkFqcGdeQXVyMTYxODUxNTA@._V1_.jpg",
   "director": "Eric Drath",
   "cast": "Hector Camacho, Eric Drath",
   "rating": "16+",
   "duration": "96 min",
   "show_time": 22,
   "description": "Included with Prime until 10/15. A hard-hitting look at the rise, fall and untimely death of one of boxing most colorful champions. The film chronicles his epic battles inside the ring, his struggles with addiction outside of it and the mystery of the crim"
  },
  {
   "id": 28,
   "title": "Sergei: Unplugged Cinema by Shailendra Singh",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMjA3NzkxMDMtYTRiZi00ZjQ1LTk4NjYtYmYwMGYyZjExMDdlXkEyXkFqcGdeQXVyMTA1MjUxNDYy._V1_.jpg",
   "director": "Shailendra Singh",
   "cast": "Sergei Polunin, Shailendra Singh",
   "rating": "13+",
   "duration": "53 min",
   "show_time": 9,
   "description": "The world's greatest ballet dancer, Sergei Polunin, as you've never seen him before - searching for answers, and himself. Raw, real, unplugged."
  },
  {
   "id": 29,
   "title": "My Grandpa Is An Alien",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMDQzNTE1ZDMtNDJjMi00YWIyLTk5MTYtMzIzMjQxNmQxYjNiXkEyXkFqcGdeQXVyMjAwOTE2MDg@._V1_.jpg",
   "director": "Marina Andree                   kop, Dr",
   "cast": "Nils Ole Oftebro, Lana Hranjec, Bill Timoney",
   "rating": "16+",
   "duration": "79 min",
   "show_time": 11,
   "description": "The entire life of a girl named Una is turned upside down when she witnesses that her grandpa is abducted by aliens. Una, in her basement, discovers that her grandpa is an alien himself whose spaceship hit the planet some time ago, and there's still his pilot, a small grumpy robot. Una and the robot have less than 24 hours to find and rescue her grandpa."
  },
  {
   "id": 30,
   "title": "Lost in Hong Kong",
   "image_url": "https://wellgousa.com/sites/default/files/2023-05/LostInHongKong-ChineseComedy-WellGoUSA-KeyArtPoster-812x1200.jpeg",
   "director": "Zheng Xu",
   "cast": "Zheng Hu, Wei Zhao, Juan Du",
   "rating": "16+",
   "duration": "114 min",
   "show_time": 13,
   "description": "Xu Lai had Dreams. He just wanted to be an Artist with a Hot Girlfriend. Now he designs bras, humors his baby-crazy wife, and caters to his loopy in-laws. But he's got a Secret Plan to find his Old Flame, and dodging his DVD-pirating, aspiring-documentarian brother-in-law may be the least of his problems. There's been a murder, and his new Hot Pursuit...might just be from the cops."
  },
  {
   "id": 31,
   "title": "All's Faire in Love",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMjA4NDQ1MDU5Nl5BMl5BanBnXkFtZTcwOTUxNzg4Ng@@._V1_FMjpg_UX1000_.jpg",
   "director": "Scott Marshall",
   "cast": "Christina Ricci, Matthew Lillard, Ann-Margret, Cedric the Entertainer",
   "rating": "PG-13",
   "duration": "108 min",
   "show_time": 15,
   "description": "A theatre troupe is about to lose its prime gig at Ye Olde Times Renaissance Faire to a rival troupe of conceited, classically-trained Shakespearean actors. This group must revive their act and find help from an unexpected source."
  },
  {
   "id": 32,
   "title": "The Last Exorcism",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTk5MjkxMjUxMF5BMl5BanBnXkFtZTcwODk5ODUwOQ@@._V1_.jpg",
   "director": "Daniel Stamm",
   "cast": "Patrick Fabian, Ashley Bell, Iris Bahr, Louis Herthum, Caleb Landry Jones",
   "rating": "PG-13",
   "duration": "88 min",
   "show_time": 16,
   "description": "HD. A phony preacher decides to record his final exorcism and expose his fraud until he discovers the very real evil w"
  },
  {
   "id": 33,
   "title": "Pati Patni Aur Woh",
   "image_url": "https://images-na.ssl-images-amazon.com/images/I/91tFCwgfEDL._RI_.jpg",
   "director": "B.R. Chopra",
   "cast": "Sanjeev Kumar, Vidya Sinha, Ranjeeta Kaur, Asrani, Om Shivpuri, Nana Palsikar, Parveen Babi",
   "rating": "13+",
   "duration": "130 min",
   "show_time": 18,
   "description": "Sharda and Ranjeet lead a happily married life with their baby boy. However, things change when Ranjeet gets attracted to his new secretary and begins an illicit affair with her."
  },
  {
   "id": 34,
   "title": "Guns of Banaras",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMDM2NjlhNWYtY2Q2MS00ZDgyLWEyMGItMDY3NzAzOTczZWE2XkEyXkFqcGdeQXVyMTA5NzIyMDY5._V1_.jpg",
   "director": "Sekhar Suri",
   "cast": "Karan Nath, Nathalia Kaur, Ganesh Venkatraman",
   "rating": "13+",
   "duration": "127 min",
   "show_time": 20,
   "description": "A sincere and diligent young man, Guddu, is very attached to his bike since it became his streak of luck. One day, when his bike gets stolen, Guddu sets out to find it but gets entangled in the world of crime when he finds out that his bike is being used to transport drugs."
  },
  {
   "id": 35,
   "title": "Zombie Massacre",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMjA3MzI4MDc1OF5BMl5BanBnXkFtZTcwMzI0MDU2OQ@@._V1_.jpg",
   "director": "Luca Boni, Marco Ristori",
   "cast": "Christian Boeving, Mike Mitchell, Tara Cardinal",
   "rating": "18+",
   "duration": "91 min",
   "show_time": 21,
   "description": "A team of soldiers who are assembled to help end a zombie outbreak in a Romanian town."
  },
  {
   "id": 36,
   "title": "The Blackout Experiment",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTc2Njg4Nzc5N15BMl5BanBnXkFtZTgwMTQxODk4MTE@._V1_.jpg",
   "director": "John David Moffat IV",
   "cast": "Uli Auliani, Troy Jones, Yasmin Irvine, Dominic Cole, Steven Synstelien, Cheverly Amalia, Stefani Rose",
   "rating": "18+",
   "duration": "80 min",
   "show_time": 22,
   "description": "6 strangers wake up inside a room garnished with weapons and are forced to kill each other or watch someone they care deeply about die."
  },
  {
   "id": 37,
   "title": "Some Freaks",
   "image_url": "https://m.media-amazon.com/images/M/MV5BOTM3NTI2MDU3Nl5BMl5BanBnXkFtZTgwNjY4MTc2MjI@._V1_.jpg",
   "director": "Ian MacAllister McDonald",
   "cast": "Lily Mae Harrington, Thomas Mann",
   "rating": "16+",
   "duration": "97 min",
   "show_time": 9,
   "description": "Two college seniors, Matt and Jill, fall in love than ever thought possible. However, when graduation comes and Jill moves cross-country to go to college and undergoes a major physical transformation - much to Matt's surprise when he arrives to visit her. While Matt struggles to accept Jill's new look, Jill begins questioning whether Matt is really the man she thought she knew."
  },
  {
   "id": 38,
   "title": "The Whistle Blower",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTkwNzU4MDk1OF5BMl5BanBnXkFtZTcwMjIyMjg4NQ@@._V1_.jpg",
   "director": "Simon Langton",
   "cast": "Michael Caine, James Fox, Nigel Havers, Sir John Gielgud, Felicity Dean",
   "rating": "PG",
   "duration": "104 min",
   "show_time": 11,
   "description": "In this gripping espionage thriller, English patriot & army vet Frank Jones (Michael Caine) is only mildly concerned when his son Bob, who works for the British Secret Service, says dirty dealings are afoot at the agency. But when Bob is murdered under mysterious circumstances, Frank's inquiries thrust him into the middle of a rat's nest of government deceit that could cost Frank his own life!"
  },
  {
   "id": 39,
   "title": "Open Five 2",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYzFmODI1OTktODJhNC00MjZlLTkxMzEtY2E1YjYwNzE4ZjU5XkEyXkFqcGdeQXVyMzExMTEwNTM@._V1_.jpg",
   "director": "Kentucker Audley",
   "cast": "Kentucker Audley, Brook Bloom, Sophia Takal, Kate Lyn Sheil, Dustin Guy Defa",
   "rating": "16+",
   "duration": "66 min",
   "show_time": 13,
   "description": "A relationship drama set amid a winter van trip from New York to New Orleans. A loose continuation of the 2010 film Open 5."
  },
  {
   "id": 40,
   "title": "Kept Woman",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTYzNzI4MjAzN15BMl5BanBnXkFtZTgwMjI5NzUyNDE@._V1_.jpg",
   "director": "Michel Poulette",
   "cast": "Courtney Ford, Shaun Benson, Andrew W. Walker, Rachel Wilson",
   "rating": "PG-13",
   "duration": "90 min",
   "show_time": 15,
   "description": "Jessica and her finally move out of the city and into their dream home on a quiet suburban street. When their strange and mysterious new neighbor lures Jessica inside his home, she finds herself imprisoned in a meticulously decorate"
  },
  {
   "id": 41,
   "title": "Jurassic Galaxy",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNTY2YjRmOWMtZDUzYi00OWZiLWEwMTQtNmRhYjlmOWYwMTJlXkEyXkFqcGdeQXVyMzYyNzI1NjU@._V1_.jpg",
   "director": "James Kondelik, Jon Kondelik",
   "cast": "Madison West, Eric Paul Erickson, Frankie Ray, Doug Bunch, Jonathan Nation, Ryan Budds",
   "rating": "13+",
   "duration": "75 min",
   "show_time": 16,
   "description": "In the near future, a ship of space explorers crash land on an unknown planet. They're soon met with some of their worst fears as they discover the planet is inhabited by monstrous dinosaurs."
  },
  {
   "id": 42,
   "title": "We Bought A Zoo: Direct Effect: Cameron Crowe",
   "image_url": "https://m.media-amazon.com/images/I/71czI0WJGBL._RI_.jpg",
   "director": "Cameron Crowe",
   "rating": "PG",
   "duration": "5 min",
   "show_time": 18,
   "description": "We Bought a Zoo is now available for download! Director Cameron Crowe lets you in on the production process. Find out what it took to make We Bought a Zoo a success."
  },
  {
   "id": 43,
   "title": "Tomorrow Never Dies",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTM1MTk2ODQxNV5BMl5BanBnXkFtZTcwOTY5MDg0NA@@._V1_FMjpg_UX1000_.jpg",
   "director": "Roger Spottiswoode",
   "cast": "Pierce Brosnan (James Bond), Jonathan Pryce (Elliot Carver), Michelle Yeoh (Wai Lin), Teri Hatcher (Paris Carver), Joe Don Baker (Wade), Ricky Jay (Henry Gupta), Gotz Otto (Stamper), Judi Dench (M), Desmond Llewelyn (Q), Vincent Schiavelli (Dr. Kaufman), Geoffrey Palmer (Admiral Roebuck), Colin Salmon (Robinson), Samantha Bond (Moneypenny), Julian Fellowes (Minister of Defense), Terence Rigby (General Bukharin), Cecilie Thomsen (Professor Inga Bergstrom), Nina Young (Tamara Steel), Daphne Deckers (PR Lady), Colin Stinton (Dr. Dave Greenwalt), Al Matthews (Master Sergeant 3), Mark Spalding (Stealth Boat Captain), Bruce Alexander (HMS Chester Captain), Anthony Green (HMS Chester Firing Officer), Christopher Bowen (Commander Richard Day), Andrew Hawkins (Lieutenant Commander Peter Hume), Dominic Shaun (HMS Devonshire Lieutenant Commander), Julian Rhind-tutt (HMS Devonshire Yeoman), Gerard Butler (HMS Devonshire Leading Seaman), Adam Barker (HMS Devonshire Sonar), Michael Byrne (Admiral Kelly), Pip Torrens (HMS Bedford Captain), Hugh Bonnevill",
   "rating": "PG-13",
   "duration": "119 min",
   "show_time": 20,
   "description": "The Carver Media Group Network seems to know the news even before it happens. It's up to James Bond to find out how and why."
  },
  {
   "id": 44,
   "title": "The Wedding Trip",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZmIxZDdmOTgtMWRlNS00N2I3LWE3MTgtZjQ0M2IzY2RmODFhXkEyXkFqcGdeQXVyNjQ1MTEyNTE@._V1_.jpg",
   "director": "Sean King",
   "cast": "Sydney Bakich, Bart Blachnio, Dani Jean, Kristjan Sokoli, Josh Kay, Stephanie S. Lindsay",
   "rating": "16+",
   "duration": "98 min",
   "show_time": 21,
   "description": "When Jack, a groomsman leaves for his best friends wedding several states away, he's asked to pick up Samantha, a stranded bridesmaid. Jack discovers they've met before and had a less than friendly past."
  },
  {
   "id": 45,
   "title": "Quantum of Solace",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMzhjYzlmYjQtYmU0Yy00NjNkLWFmOTQtZjQxZWU4NjY1Y2M4XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
   "director": "Marc Forster",
   "cast": "Daniel Craig, Olga Kurylenko, Mathieu Amalric, Giancarlo Giannini, Jeffrey Wright, Judi Dench",
   "rating": "PG-13",
   "duration": "106 min",
   "show_time": 22,
   "description": "HD. Seeking vengeance for his lover's death, James Bond uncovers a conspiracy to take control of a country's most precious natural resource."
  },
  {
   "id": 46,
   "title": "Matthew Bourne's The Car Man",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDdlZWQ2MTktMzA4Yy00ODVjLTlmOGMtZGNjNDM1OGYzY2RkXkEyXkFqcGdeQXVyNDA1MTEyMjI@._V1_.jpg",
   "director": "Matthew Bourne",
   "cast": "Christopher Trenfield, Zizi Strallen, Dominic North, Kate Lyons, Alan Vincent",
   "rating": "13+",
   "duration": "98 min",
   "show_time": 9,
   "description": "Loosely based on Bizet's popular opera Carmen, The Car Man changes the 19th-century Spanish cigarette factory of the opera to a greasy garage-diner in the American mid-west of the 60s. The arrival of a handsome stranger disturbs the dreams and passions of those who live and work there."
  },
  {
   "id": 47,
   "title": "American Renegades",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTQ5Njk3MTY2MV5BMl5BanBnXkFtZTcwOTY3Mjc5Mg@@._V1_.jpg",
   "director": "Steven Quale",
   "cast": "Sullivan Stapleton, Charlie Bewley, Joshua Henry, Diarmaid Murtagh, Dimitri Leonidas, J. K. Simmons",
   "rating": "PG-13",
   "duration": "105 min",
   "show_time": 11,
   "description": "A team of Navy SEALs is hired to salvage Nazi gold stored in a bank vault in a submerged town at the bottom of a Bosnian lake."
  },
  {
   "id": 48,
   "title": "A-Team: Life After Film School with Joe Carnahan",
   "image_url": "https://darkroom.bbfc.co.uk/751/https://m.media-amazon.com/images/M/MV5BMTc4ODc4NTQ1N15BMl5BanBnXkFtZTcwNDUxODUyMw@@._V1_.jpg:4ea68ddabb425ccd4aca8fb2e106c8d0",
   "director": "20th Century Fox",
   "rating": "PG-13",
   "duration": "10 min",
   "show_time": 13,
   "description": "The A-Team is now available for download! A group of film students get the opportunity of a lifetime... to interview director Joe Carnahan of The A-Team! Join the students as they learn about the industry through the words of Joe himself."
  },
  {
   "id": 49,
   "title": "5th Street",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTU0MjgxNTU0MF5BMl5BanBnXkFtZTgwNjQxNTg4MDE@._V1_.jpg",
   "director": "Alex Meader",
   "cast": "Eric Arthur Martinez, Christian Monzon, Joe Voltierra, Annie Fetchu, Adam Lopez, Anne Leighton, Jason Giuliano, Orson Chaplin",
   "rating": "16+",
   "duration": "103 min",
   "show_time": 15,
   "description": "A vengeful husband takes on gangs and corrupt cops in this gritty vigilante thriller featuring Christian Monzon (Kill Speed) and Jason Giuliano (Red)."
  },
  {
   "id": 50,
   "title": "The Starving Games",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTgwOTk2OTY4MV5BMl5BanBnXkFtZTgwMTU5MjE0MDE@._V1_.jpg",
   "director": "Jason Friedberg, Aaron Seltzer",
   "cast": "Maiara Walsh, Cody Christian, Brant Daugherty, Diedrich Bader",
   "rating": "PG-13",
   "duration": "82 min",
   "show_time": 16,
   "description": "In this Hunger Games spoof, Kantmiss Evershot must fight for her life in the 75th annual Starving Games, where she could also win an old ham, a coupon for a foot-long sub, and a partially eaten pickle."
  },
  {
   "id": 51,
   "title": "Happy Little Bunnies",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMGE2NjNhMTQtZmFjOS00YWNkLWI0ZjQtOTgwZGMzNWUzNmFhXkEyXkFqcGdeQXVyMjYwMzA4MDc@._V1_FMjpg_UX1000_.jpg",
   "director": "Patrick McConnell",
   "cast": "Jon-Scott Clark, Simon Manley, Sophie Toland, Lynne Payne",
   "rating": "18+",
   "duration": "98 min",
   "show_time": 18,
   "description": "A psychotic, bunny-masked serial killer is on the prowl, carving up local perverts. Meanwhile, a disturbed young man's therapy session takes a dark and violent turn. Is his therapist the bunny-masked killer? From the makers of How Not To Work & Claim Benefits (& other useful information for wasters)."
  },
  {
   "id": 52,
   "title": "Chinnanjiru Kiliye",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNTM4YjAwYzktNjBkNi00NTdhLTgzOTctOWYyNWUyZTgzZjBlXkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_.jpg",
   "director": "Sabarinathan Muthupandian",
   "cast": "Prasanna Venkatesan, Sandra Nair",
   "rating": "13+",
   "duration": "120 min",
   "show_time": 20,
   "description": "A naturopathy practitioner with a strong distrust of allopathic treatments goes after the kidnappers of his daughter and expose a medical crime.dr"
  },
  {
   "id": 53,
   "title": "Bride Wars",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMTUyNTg2OTUwN15BMl5BanBnXkFtZTgwNzEzMzg5MTI@._V1_FMjpg_UX1000_.jpg",
   "director": "Gary Winick",
   "cast": "Kate Hudson, Anne Hathaway, Kristen Johnston, Bryan Greenberg, Candice Bergen",
   "rating": "PG",
   "duration": "89 min",
   "show_time": 21,
   "description": "When a clerical error causes a clash in wedding dates, two best friends who'd do anything for each other find themselves in a no-holds-barred, take-no-prisoners struggle that threatens to erupt into all-out war."
  },
  {
   "id": 54,
   "title": "Blue Moon",
   "image_url": "https://m.media-amazon.com/images/M/MV5BOGJhN2UxMmMtZWQ1NS00MDY3LThjN2ItNTM3ZDBlZjgyYjEzXkEyXkFqcGdeQXVyMTMyOTQ2MTE5._V1_.jpg",
   "director": "Ron Lagomarsino",
   "cast": "Sharon Lawrence, Jeffrey Nordling, Richard Kiley, Kim Hunter",
   "rating": "18+",
   "duration": "92 min",
   "show_time": 22,
   "description": "Blue Moon is a multi-layered story about the complexities and conflicts of a family tearing apart at the seams. Sheila and Jimmy Keating run a financially-strapped restaurant and fishing business in Maine which is gradually taking a toll on their marriage. It takes a huge storm at sea for them to rekindle their love for one another."
  },
  {
   "id": 55,
   "title": "Ardha Shathabdham",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNjU4MTVmYzEtOWNkZi00YmNhLWI0MDQtM2Q5NjMzOTYxYmFhXkEyXkFqcGdeQXVyMTI1NDAzMzM0._V1_FMjpg_UX1000_.jpg",
   "director": "Rawindra Pulle",
   "cast": "Karthik Rathnam, Naveen Chandra, Krishna Priya, Sai Kumar, Suhas, Aamani, Pavitra Lokesh, Subhaleka Sudhakar, Ajay",
   "rating": "13+",
   "duration": "116 min",
   "show_time": 9,
   "description": "After five decades of Independence, India's rural landscape still throws up unanswerable questions. Can a love story bring a revolution? Witness this earthy love story of Ardhashatabdam set in the early 2000s."
  },
  {
   "id": 56,
   "title": "Wild Fire",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDY0ZmRmNzAtMTZjYS00MzY3LTlmNGEtNGY4NjlkOGVmMzQxXkEyXkFqcGdeQXVyMTE5NDkxMA@@._V1_.jpg",
   "director": "Esther Abah",
   "cast": "Wole Ojo Mary Lazarus Neye Balogun",
   "rating": "16+",
   "duration": "80 min",
   "show_time": 11,
   "description": "Wild Fire is a drama about a young man, Ezie, who has been single for a while due to the high standards he has set for whoever is supposed to become his partner. Ezie finally meets Shizzle, his favourite actress and all-time crush, and they both get married despite the warnings from his family."
  },
  {
   "id": 57,
   "title": "Tooth Fairy 2",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMzE1MTZlMjEtOTFmYS00YjM0LTkxODYtYjY1NmMxNmRhMmEyXkEyXkFqcGdeQXVyNDgyODgxNjE@._V1_.jpg",
   "director": "Alex Zamm",
   "cast": "Larry Guthrie, Brady Reiter, Erin Beute, David Mackey",
   "rating": "PG",
   "duration": "90 min",
   "show_time": 13,
   "description": "When dreamer Larry Guthrie (Larry the Cable Guy) loses his first love to the town hot shot, he decides to win her back by volunteering with the local children at her after-school program. But when Larry accidentally tells the kids the tooth fairy is make"
  },
  {
   "id": 58,
   "title": "The Rocker",
   "image_url": "https://m.media-amazon.com/images/M/MV5BYWQ3NzY4NGUtZTlhZC00Njc1LWI3Y2QtY2U3NWEzMzJkYzJiXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
   "director": "Peter Cattaneo",
   "cast": "Rainn Wilson, Christina Applegate, Teddy Geiger, Josh Gad, Emma Stone, Jeff Garlin, Jane Lynch, Jason Sudeikis, Will Arnett, Howard Hesseman, Fred Armisen, Bradley Cooper, Lonny Ross, Jon Glaser, Jane Krakowski, Samantha Weinstein, Demetri Martin, Aziz Ansari, Ellie Knaus, Laura DeCarteret, Steve Adams, Mark Forward, Vik Sahay, Brittany Allen, Jonathan Malen, Rebecca Northan, Keir Gilchrist, Simon Sinn, SuChin Pak, Ennis Esmer, Nicole Arbour, Wesley Morgan, Tanya Bevan, Marvin Karon, Sandi Ross, Talia Russo, Jon Cor, Darrel Gamotin, Angela Maiorano, Nick Spencer, Allan Roberto, Patrick Hagarty, Jessica Porter, Dave Kiner, Guy Sanvido, Christian Potenza, Pete Best, Jessica Barrow, Jordan Lawson, Richard Wadham",
   "rating": "PG-13",
   "duration": "102 min",
   "show_time": 15,
   "description": "Rainn Wilson (TV's The Office) drums up huge laughs in this hilarious comedy about living in a rock 'n' roll dream...and waking up in a midlife crisis."
  },
  {
   "id": 59,
   "title": "Shanghai Knights",
   "image_url": "https://m.media-amazon.com/images/M/MV5BNDc2MzZjODAtYTI3NC00OTBhLTk5NDAtOWIzYmFmZDJlOTA4XkEyXkFqcGdeQXVyNTA3MTU2MjE@._V1_.jpg",
   "director": "David Dobkin",
   "cast": "Jackie Chan, Owen Wilson, Donnie Yen, Aidan Gillen",
   "rating": "PG-13",
   "duration": "114 min",
   "show_time": 16,
   "description": "HD. Jackie Chan and Owen Wilson hop back in the saddle in this sequel to Shanghai Noon"
  },
  {
   "id": 60,
   "title": "I Can't Breathe",
   "image_url": "https://m.media-amazon.com/images/M/MV5BZGI5ZTU2M2YtZWY4MC00ZDFhLTliYTItZTk1NjdlN2NkMzg2XkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_.jpg",
   "director": "Kishore Tummala",
   "cast": "Mechielle Anderson, Marc Jean, Christopher David Roch, Melissa Martinelli, Dominic Costa, Gina Martino, Marc Holladay, Wendi Smith, Dave Shaver, Mike Sutton, Tariq Rasheed, Stefan Matthews, Jennifer Ann Fernandez, Tracy Suttles",
   "rating": "18+",
   "duration": "32 min",
   "show_time": 18,
   "description": "An African American single mother's emotional journey after her young son was gunned down by a police officer during a routine traffic stop and the consequences for both sides. Written & Directed by Kishore Tummala."
  },
  {
   "id": 61,
   "title": "12 Dates of Christmas",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMDhmOWU5Y2EtNjlkYi00ODY4LTlhNDktM2U1ZTVmYzllOTE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
   "director": "Jason Friedberg, Aaron Seltzer",
   "rating": "PG",
   "duration": "87 min",
   "show_time": 20,
   "description": "Setup on a Christmas Eve date, a woman must relive the date over and over."
  },
  {
   "id": 62,
   "title": "10 Things I Hate About You",
   "image_url": "https://m.media-amazon.com/images/M/MV5BMmVhZjhlZDYtMDAwZi00MDcyLTgzOTItOWNiZjY0YmE0MGE0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg",
   "director": "Gil Junger",
   "cast": "Heath Ledger, Julia Stiles, Joseph Gordon-Levitt, Larisa Oleynik, David Krumholtz, Andrew Keegan, Susan May Pratt, Gabrielle Union, Larry Miller, Daryl \"Chill\" Mitchell, Allison Janney, David Leisure, Greg Jackson, Kyle Cease, Terence Heuston, Cameron Fraser, Eric Reidman, Quinn Maixner, Demegio Kimbrough, Todd Butler, Dennis Mosley, Bianca Kajlich, Nick Vukelic, Benjamin Laurance, Aidan Kennedy, Jelani Quinn, Jesse Dyer, Aaron Therol, Carlos LaCamara, Heathre Taylor, Joshua Thorpe, J. R. Johnson, Wendy Gottlieb, Brian Hood, Travis Muller, Ari Karczag, Laura Kenny, Alice Evans, Jesper Inglis, Nick Brown, Monique Powell, Brian Mashburn, Kay Hanley, Michael Eisenstein",
   "rating": "PG-13",
   "duration": "97 min",
   "show_time": 21,
   "description": "On the first day at his new school, Cameron instantly falls for Bianca the gorgeous girl of his dreams."
  }
 ]



 
export default data;
